#!/usr/bin/env node
/**
 * XT-Shopify 多国家主题工具（AU / US）
 *
 * 工作流：
 *   pull:us（首次）  线上完整代码 → dist/us/（提交 git，各国天然分开）
 *   dev:us           dist/us → .dev/us（不提交的预览区）→ shopify theme dev
 *                    开发中改根目录共享代码，保存后实时合并进 .dev/us 热刷新；
 *                    退出时把预览区里的配置改动自动回收进 dist/us
 *   build            根目录共享代码正式同步进 dist/us、dist/au（不覆盖该国已定制文件）
 *   push:us          dist/us 推送线上
 *
 * 文件归属：
 *   共享代码（sections/snippets/assets/…/基准模板）  只改根目录，build 同步进各国
 *   config/settings_data.json                        属于各国（dist/<国>/），build 只在缺失时种入
 *   templates/*.json                                 跟随基准，除非该国改过（.base-manifest.json 指纹记录）
 *
 * 命令：node scripts/sync.mjs <build|dev|push|pull|capture|list> [国|all] [选项]
 * 选项：--dry-run / push: --code-only --prune --allow-live / pull: --config-only
 */

import { spawn } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DEV_DIR = path.join(ROOT, '.dev'); // dev 预览区（纯一次性，可整体删除）
const DIST_DIR = path.join(ROOT, 'dist');
const STORES_FILE = path.join(ROOT, 'stores.json'); // 店铺注册表（国家 → 域名/主题ID，提交 git）
const TOKENS_FILE = path.join(ROOT, 'tokens.local.json'); // 各店 Theme Access token（gitignored）
const MANIFEST_NAME = '.base-manifest.json';

// 主题结构白名单：只有这些目录会进入 dist/.dev，其余（docs/、scripts/、.dev/ 等）绝不进入
const THEME_DIRS = ['assets', 'blocks', 'config', 'layout', 'locales', 'sections', 'snippets', 'templates'];

// 写入产物目录的 .shopifyignore（推送/拉取/预览时 CLI 以该目录内此文件为准）
const DIST_SHOPIFYIGNORE = [
  '# generated by scripts/sync.mjs',
  '.base-manifest.json',
  '.DS_Store',
  'Thumbs.db',
  '*.log',
  '',
].join('\n');

// ---------- CLI 参数 ----------

const argv = process.argv.slice(2);
const [cmd, ...rest] = argv;
const positional = rest.filter((a) => !a.startsWith('--'));
const flags = new Set(rest.filter((a) => a.startsWith('--')).map((a) => a.replace(/^--/, '')));

// ---------- 基础工具 ----------

function die(msg, code = 1) {
  console.error(`✖ ${msg}`);
  process.exit(code);
}

function walk(dir, rootDir, cb) {
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (e.name.startsWith('.')) continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, rootDir, cb);
    else if (e.isFile()) cb(p, path.relative(rootDir, p).split(path.sep).join('/'));
  }
}

function shaFile(file) {
  return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

/** 键序无关的 JSON 规范序列化（用于语义比较） */
function stableJson(v) {
  if (Array.isArray(v)) return `[${v.map(stableJson).join(',')}]`;
  if (v && typeof v === 'object') {
    return `{${Object.keys(v).sort().map((k) => `${JSON.stringify(k)}:${stableJson(v[k])}`).join(',')}}`;
  }
  return JSON.stringify(v);
}

/**
 * 语义哈希：JSON 文件按解析后的内容计算（键序/格式差异不算差异），
 * 解析失败退化为原始字节哈希。Shopify CLI 写 JSON 会重排格式，
 * 字节比较会把所有经过 dev/pull 的模板误判为「该国定制」，导致共享改动无法传播。
 */
function semHash(file) {
  try {
    const text = fs.readFileSync(file, 'utf8');
    try {
      return crypto.createHash('sha256').update(stableJson(JSON.parse(text))).digest('hex');
    } catch {
      return `raw:${crypto.createHash('sha256').update(text).digest('hex')}`;
    }
  } catch {
    return null;
  }
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function writeJsonIfChanged(file, value) {
  const body = `${JSON.stringify(value, null, 2)}\n`;
  if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== body) fs.writeFileSync(file, body);
}

function writeIfChanged(file, body) {
  if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== body) fs.writeFileSync(file, body);
}

function needsCopy(src, dest) {
  try {
    const [s, d] = [fs.statSync(src), fs.statSync(dest)];
    return s.size !== d.size || s.mtimeMs > d.mtimeMs;
  } catch {
    return true;
  }
}

function pruneEmptyDirs(dir, top) {
  let empty = true;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (!pruneEmptyDirs(p, top)) empty = false;
    } else empty = false;
  }
  if (empty && dir !== top) fs.rmdirSync(dir);
  return empty;
}

function processExists(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch (e) {
    return e.code === 'EPERM';
  }
}

// ---------- 店铺注册表 ----------

function loadStores() {
  if (!fs.existsSync(STORES_FILE)) die(`未找到 ${path.relative(ROOT, STORES_FILE)}，请先创建店铺注册表`);
  let stores;
  try {
    stores = readJson(STORES_FILE).stores;
  } catch (e) {
    die(`stores.json 解析失败：${e.message}`);
  }
  for (const [key, s] of Object.entries(stores)) {
    if (!s.domain || !s.themeId) die(`stores.json 中 "${key}" 缺少 domain 或 themeId`);
  }
  return stores;
}

function getStore(country, stores) {
  const s = stores[country];
  if (!s) die(`未知国家 "${country}"，可用：${Object.keys(stores).join(', ')}（或 all）`);
  return s;
}

function resolveCountries(target, stores) {
  if (!target || target === 'all') return Object.keys(stores);
  const cs = target.split(',').map((t) => t.trim()).filter(Boolean);
  for (const c of cs) getStore(c, stores);
  return cs;
}

function tokenEnvFor(country) {
  if (!fs.existsSync(TOKENS_FILE)) return {};
  try {
    const token = readJson(TOKENS_FILE)[country];
    if (token) return { SHOPIFY_CLI_THEME_TOKEN: token };
  } catch {
    console.warn('⚠ tokens.local.json 解析失败，忽略 token');
  }
  return {};
}

function runShopify(args, country) {
  return new Promise((resolve) => {
    const child = spawn(['shopify', ...args].join(' '), {
      shell: true,
      stdio: 'inherit',
      cwd: ROOT,
      env: { ...process.env, ...tokenEnvFor(country) },
    });
    child.on('exit', (code) => resolve(code ?? 1));
    child.on('error', (err) => {
      console.error(`✖ 无法启动 shopify CLI：${err.message}`);
      console.error('  请确认已安装：npm i -g @shopify/cli @shopify/theme');
      resolve(1);
    });
  });
}

// ---------- 合并（build 与 dev 热同步共用同一套规则） ----------

function isTemplateJson(rel) {
  return rel.startsWith('templates/') && rel.endsWith('.json');
}

/**
 * 把根目录共享代码合并进目标目录（dist/<国> 或 .dev/<国>）：
 *   - 代码文件：增量覆盖 + 镜像删除，以根目录为准；
 *   - config/settings_data.json：只在缺失时种入一次；
 *   - templates/*.json：未被该国改过的跟随基准更新（指纹记录于目标目录的
 *     .base-manifest.json），已定制的不覆盖。
 */
function mergeRootInto(destDir) {
  fs.mkdirSync(destDir, { recursive: true });
  const manifestFile = path.join(destDir, MANIFEST_NAME);
  const oldManifest = fs.existsSync(manifestFile) ? readJson(manifestFile) : {};

  const base = new Map();
  for (const d of THEME_DIRS) walk(path.join(ROOT, d), ROOT, (abs, r) => base.set(r, abs));

  let copied = 0;
  let kept = 0;
  let removed = 0;
  let protectedN = 0;
  const manifest = {};

  for (const [r, src] of base) {
    const dest = path.join(destDir, r);
    if (r === 'config/settings_data.json') {
      if (fs.existsSync(dest)) protectedN++;
      else {
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.copyFileSync(src, dest);
        copied++;
      }
      continue;
    }
    if (isTemplateJson(r)) {
      if (!fs.existsSync(dest)) {
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.copyFileSync(src, dest);
        manifest[r] = semHash(src);
        copied++;
        continue;
      }
      const destSem = semHash(dest);
      const baseSem = semHash(src);
      const recorded = oldManifest[r];
      // 判定顺序很关键：内容与基准语义一致 → 必是原版（旧格式记录自动收编）；
      // 否则记录与当前内容一致 → 上次打包以来的原版（基准更新可传播）；再次之 → 该国定制
      const pristine = destSem === baseSem || (recorded && recorded === destSem);
      if (!pristine) {
        protectedN++;
        continue;
      }
      if (destSem !== baseSem) {
        fs.copyFileSync(src, dest);
        copied++;
      } else kept++;
      manifest[r] = baseSem;
      continue;
    }
    if (!fs.existsSync(dest) || needsCopy(src, dest)) {
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.copyFileSync(src, dest);
      copied++;
    } else kept++;
  }

  // 镜像删除：只作用于主题白名单目录内部（dest 根下的其他文件——如 .dev 里的
  // stores.json/tokens——不归主题管辖，绝不触碰）
  for (const d of THEME_DIRS) {
    walk(path.join(destDir, d), destDir, (abs, r) => {
      if (r === 'config/settings_data.json') return;
      if (base.has(r)) return;
      if (isTemplateJson(r)) {
        const recorded = oldManifest[r];
        if (recorded && recorded === semHash(abs)) {
          fs.rmSync(abs);
          removed++;
        }
        return;
      }
      fs.rmSync(abs);
      removed++;
    });
  }
  pruneEmptyDirs(destDir, destDir);

  writeJsonIfChanged(manifestFile, manifest);
  writeIfChanged(path.join(destDir, '.shopifyignore'), DIST_SHOPIFYIGNORE);
  return { total: base.size, copied, kept, removed, protected: protectedN };
}

// ---------- dev（预览区 .dev/<国>） ----------

/** 把预览区（.dev 根）里改过的配置（settings_data + 模板）回收进 dist/<国>。 */
function captureBack(country) {
  const dist = path.join(DIST_DIR, country);
  const marker = path.join(DEV_DIR, 'active.json');
  if (fs.existsSync(marker)) {
    try {
      const active = readJson(marker);
      if (active.country && active.country !== country) {
        return die(`预览区当前是 ${active.country} 的会话，不能作为 ${country} 回收`);
      }
    } catch { /* 损坏的标记忽略 */ }
  }
  if (!fs.existsSync(path.join(DEV_DIR, 'config', 'settings_data.json'))) {
    return die('预览区 .dev/ 中没有主题内容，无可回收');
  }
  const targets = ['config/settings_data.json'];
  walk(path.join(DEV_DIR, 'templates'), path.join(DEV_DIR, 'templates'), (abs, r) => {
    if (r.endsWith('.json')) targets.push(`templates/${r}`);
  });
  let saved = 0;
  for (const rel of targets) {
    const src = path.join(DEV_DIR, rel);
    if (!fs.existsSync(src)) continue;
    const dest = path.join(dist, rel);
    if (!fs.existsSync(dest) || semHash(src) !== semHash(dest)) {
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.copyFileSync(src, dest);
      saved++;
      console.log(`  ↳ ${rel} 已回收进 dist/${country}/`);
    }
  }
  // 被改过的模板会因语义指纹不符在下次 build 时自动转为该国定制，无需改 manifest
  console.log(`[capture:${country}] 完成（${saved} 个文件更新）`);
}

async function dev(country, stores) {
  const store = getStore(country, stores);
  const dist = path.join(DIST_DIR, country);
  if (!fs.existsSync(path.join(dist, '.shopifyignore'))) {
    console.log(`[dev:${country}] dist/${country} 不存在，先打包…`);
    mergeRootInto(dist);
  }

  // .dev 是唯一预览区，同一时间只能承载一个国家
  const marker = path.join(DEV_DIR, 'active.json');
  if (fs.existsSync(marker)) {
    try {
      const active = readJson(marker);
      if (active.pid && processExists(active.pid)) {
        return die(`已有 ${active.country} 的 dev 会话在运行（PID ${active.pid}）。每次只能运行一个国家的开发环境，请先退出再切换。`);
      }
    } catch { /* 损坏的标记直接覆盖 */ }
  }
  fs.mkdirSync(DEV_DIR, { recursive: true });
  fs.writeFileSync(marker, `${JSON.stringify({ country, pid: process.pid }, null, 2)}\n`);

  // 重建预览区：.dev 根 = 该国内容（只清主题目录，保留 stores.json / tokens 等注册文件）
  for (const d of THEME_DIRS) fs.rmSync(path.join(DEV_DIR, d), { recursive: true, force: true });
  fs.rmSync(path.join(DEV_DIR, MANIFEST_NAME), { force: true });
  fs.rmSync(path.join(DEV_DIR, '.shopifyignore'), { force: true });
  for (const d of THEME_DIRS) {
    const src = path.join(dist, d);
    if (fs.existsSync(src)) fs.cpSync(src, path.join(DEV_DIR, d), { recursive: true });
  }
  if (fs.existsSync(path.join(dist, MANIFEST_NAME))) {
    fs.copyFileSync(path.join(dist, MANIFEST_NAME), path.join(DEV_DIR, MANIFEST_NAME));
  }
  const m = mergeRootInto(DEV_DIR);
  // 预览区专属忽略：会话标记不上传（.dev 是纯一次性预览区，整体 gitignored）
  writeIfChanged(path.join(DEV_DIR, '.shopifyignore'), `${DIST_SHOPIFYIGNORE}active.json\n`);
  console.log(`[dev:${country}] 预览区 .dev/ 已载入 ${country} 内容（含未 build 的共享改动 ${m.copied} 个文件）`);

  // 改根目录共享代码 → 保存 → 实时合并进预览区 → shopify dev 热刷新
  const watchers = [];
  let timer = null;
  const syncNow = () => {
    const r = mergeRootInto(DEV_DIR);
    if (r.copied || r.removed) console.log(`[sync] 共享代码变更 → .dev/（${r.copied} 更新 / ${r.removed} 移除）`);
  };
  for (const d of THEME_DIRS) {
    const root = path.join(ROOT, d);
    if (!fs.existsSync(root)) continue;
    try {
      const w = fs.watch(root, { recursive: true }, () => {
        clearTimeout(timer);
        timer = setTimeout(syncNow, 200);
      });
      w.on('error', () => {});
      watchers.push(w);
    } catch {
      console.warn(`⚠ 无法监听 ${d}/，热同步对该目录不可用`);
    }
  }

  const args = [
    'theme', 'dev',
    '--path', '.dev',
    '--store', store.domain,
    '--theme-editor-sync',
    // 不传 --theme：CLI 自动使用店铺的临时 Development 沙箱主题。
    // 若指定真实主题 ID，CLI 会与其双向同步，可能把本地内容覆盖到线上（严禁）。
    // 预览策略：预览区即事实来源，本地多出的文件直接保留（否则 CLI 弹交互确认，后台场景直接失败）
    '--reconciliation-strategy', 'keep-local',
  ];
  console.log(`\n> shopify ${args.join(' ')}\n`);
  let sigintCount = 0;
  const onSigint = () => {
    if (++sigintCount >= 2) {
      console.warn(`\n⚠ 强制退出（预览区配置改动未回收，可稍后运行 yarn capture:${country} 补救）`);
      process.exit(130);
    }
  };
  process.on('SIGINT', onSigint);
  const code = await runShopify(args, country);
  clearTimeout(timer);
  watchers.forEach((w) => w.close());
  process.removeListener('SIGINT', onSigint);
  console.log(`\n[dev:${country}] 会话结束（exit ${code}），回收预览区配置改动…`);
  captureBack(country);
  fs.rmSync(marker, { force: true });
  process.exit(code);
}

// ---------- push ----------

async function push(countries, stores) {
  let failed = 0;
  for (const c of countries) {
    const store = getStore(c, stores);
    const r = mergeRootInto(path.join(DIST_DIR, c));
    console.log(`[build:${c}] dist/${c} 共 ${r.total} 个基准文件（${r.copied} 拷贝 / ${r.removed} 移除 / ${r.protected} 该国文件受保护）`);
    const args = ['theme', 'push', '--path', `dist/${c}`, '--store', store.domain, '--theme', String(store.themeId)];
    if (!flags.has('prune')) args.push('--nodelete');
    if (flags.has('code-only')) args.push('--ignore', 'config/settings_data.json');
    if (flags.has('allow-live')) args.push('--allow-live');
    if (flags.has('dry-run')) {
      console.log(`[dry-run] > shopify ${args.join(' ')}\n`);
      continue;
    }
    console.log(`\n> shopify ${args.join(' ')}\n`);
    const code = await runShopify(args, c);
    if (code !== 0) {
      failed++;
      console.error(`✖ push ${c} 失败（exit ${code}），继续下一家`);
    }
  }
  if (failed) die(`${failed} 个国家推送失败`);
}

// ---------- pull ----------

/** pull 后重建指纹清单：与基准一致的模板标记为共享原版，基准改动可继续向该国传播。 */
function remarkPristine(country) {
  const dist = path.join(DIST_DIR, country);
  const manifestFile = path.join(dist, MANIFEST_NAME);
  const old = fs.existsSync(manifestFile) ? readJson(manifestFile) : {};
  const manifest = {};
  walk(path.join(dist, 'templates'), path.join(dist, 'templates'), (abs, r) => {
    if (!r.endsWith('.json')) return;
    const baseFile = path.join(ROOT, 'templates', r);
    if (fs.existsSync(baseFile)) {
      const ds = semHash(abs);
      if (ds === semHash(baseFile)) manifest[`templates/${r}`] = ds;
    }
  });
  // 保留 templates 之外的既有记录（目前只有 templates，稳妥起见合并）
  writeJsonIfChanged(manifestFile, { ...old, ...manifest });
}

async function pull(countries, stores) {
  for (const c of countries) {
    const store = getStore(c, stores);
    const dist = path.join(DIST_DIR, c);
    const configOnly = flags.has('config-only');
    if (configOnly) {
      // 只拉配置时 dist 必须已是完整主题，缺失则先打包
      if (!fs.existsSync(path.join(dist, '.shopifyignore'))) mergeRootInto(dist);
    } else {
      fs.mkdirSync(dist, { recursive: true });
    }
    const args = ['theme', 'pull', '--path', `dist/${c}`, '--store', store.domain, '--theme', String(store.themeId)];
    if (configOnly) args.push('--only', 'config/settings_data.json', '--only', 'templates/*.json');
    if (flags.has('dry-run')) {
      console.log(`[dry-run] > shopify ${args.join(' ')}`);
      console.log(`[dry-run] 线上内容将写入 dist/${c}/（该国即分开保存）\n`);
      continue;
    }
    console.log(`\n> shopify ${args.join(' ')}\n`);
    const code = await runShopify(args, c);
    if (code === 0) {
      remarkPristine(c);
      console.log(`[pull:${c}] 完成，线上内容已写入 dist/${c}/`);
    } else {
      console.error(`✖ pull ${c} 失败（exit ${code}）`);
    }
  }
}

// ---------- list ----------

function list(stores) {
  const tokenFile = fs.existsSync(TOKENS_FILE) ? readJson(TOKENS_FILE) : {};
  console.log('店铺注册表（stores.json）：\n');
  for (const [key, s] of Object.entries(stores)) {
    const dist = path.join(DIST_DIR, key);
    let distN = 0;
    let settings = '未初始化（yarn pull:' + key + ' 或 yarn build）';
    let templates = '';
    if (fs.existsSync(dist)) {
      walk(dist, dist, (abs, r) => {
        if (r === MANIFEST_NAME || r === '.shopifyignore') return;
        distN++;
      });
      settings = fs.existsSync(path.join(dist, 'config', 'settings_data.json')) ? '已就绪' : '缺失';
      const manifest = fs.existsSync(path.join(dist, MANIFEST_NAME)) ? readJson(path.join(dist, MANIFEST_NAME)) : {};
      let total = 0;
      let customized = 0;
      walk(path.join(dist, 'templates'), path.join(dist, 'templates'), (abs, r) => {
        if (r.endsWith('.json')) {
          total++;
          if (!manifest[`templates/${r}`]) customized++;
        }
      });
      templates = total ? `共 ${total} 个（该国定制 ${customized}）` : '无';
    }
    console.log(`  ${key}（${s.label || ''}）`);
    console.log(`    域名       ${s.domain}`);
    console.log(`    主题 ID    ${s.themeId}`);
    console.log(`    token      ${tokenFile[key] ? '已配置' : '未配置（首次将触发浏览器登录）'}`);
    console.log(`    dist       ${distN ? `${distN} 个文件` : '未构建'}；settings_data：${settings}；模板：${templates}\n`);
  }
}

// ---------- main ----------

const HELP = `XT-Shopify 多国家主题工具

工作流：pull（首次全量）→ dev（.dev/ 预览区热同步）→ build → push

店铺注册表：stores.json（仓库根目录，国家 → 域名/主题ID）
token：tokens.local.json（仓库根目录，gitignored，模板见 tokens.local.json.example）

命令：
  build <国|all>    根目录共享代码 → dist/<国>/（不覆盖该国已定制的配置/模板）
  dev <国>           dist/<国> → .dev/ 预览区（单一会话，同一时间只能跑一个国家）
                     → shopify theme dev；改根目录共享代码实时热刷新；
                     退出时自动回收预览区配置改动进 dist/<国>
  push <国|all>      build 后推送（默认 --nodelete；不带国家 = 全部）
  pull <国|all>      线上完整代码 → dist/<国>/；--config-only 只拉 settings_data+模板
  capture <国>       手动把 .dev/ 预览区的配置改动回收进 dist/<国>（dev 异常退出后补救）
  list               店铺注册表与各国 dist 状态

选项：
  --dry-run          只打印命令与动作，不执行
  --code-only        (push) 追加 --ignore config/settings_data.json，不动线上主题设置
  --prune            (push) 去掉 --nodelete，允许删除线上多余文件
  --allow-live       (push) 目标为线上主题时放行
  --config-only      (pull) 只拉配置，不拉代码

示例：
  yarn pull:us && yarn pull:au     # 首次：两国线上代码分别进 dist/us、dist/au
  yarn dev:us                      # US 开发（改共享代码 → 保存即热刷新）
  yarn build                       # 改完提交前：共享代码同步进两国 dist
  yarn push:us                     # 发布 US`;

const stores = loadStores();

switch (cmd) {
  case 'build': {
    for (const c of resolveCountries(positional[0], stores)) {
      const r = mergeRootInto(path.join(DIST_DIR, c));
      console.log(`[build:${c}] dist/${c} 共 ${r.total} 个基准文件（${r.copied} 拷贝 / ${r.kept} 未变 / ${r.removed} 移除 / ${r.protected} 该国文件受保护）`);
    }
    break;
  }
  case 'dev':
    await dev(positional[0], stores);
    break;
  case 'push':
    await push(resolveCountries(positional[0], stores), stores);
    break;
  case 'pull':
    await pull(resolveCountries(positional[0], stores), stores);
    break;
  case 'capture':
    for (const c of resolveCountries(positional[0], stores)) captureBack(c);
    break;
  case 'list':
    list(stores);
    break;
  default:
    console.log(HELP);
    if (cmd) console.error(`\n✖ 未知命令 "${cmd}"`);
    process.exit(cmd ? 1 : 0);
}
